export type FertiSmartPatientModel = {
  fileId?: number;
  mrn?: string;
  mrnLeg?: string;
  // titleId?: number;
  firstName?: string;
  middleName?: string;
  lastName?: string;
  maidenName?: string;
  arabicName?: string;
  dob?: string;
  age?: string;
  contactNumber?: string;
  alternativeContactNumber?: string;
  registerDate?: string;
  emailAddress?: string;
  sex?: 0 | 1;
  identityIdType?: { id?: number; name?: string };
  branch?: { id?: number; name?: string };
  nationality?: { id?: number; name?: string };
  // nationalityId?: number;
  identityId?: string;
  // occupationStatusId?: number;
  occupation?: string;
  // branchId?: number;
  // oldBranchId?: number;
  // physicianId?: number;
  type?: number;
  // bloodTypeId?: number;
  // fileDisabled?: number;
};
